#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define GAME_SCREEN_WIDTH 160
#define GAME_SCREEN_HEIGHT 144

#define GAME_HUD_HEIGHT 12

#define GAME_PLAYFIELD_WIDTH GAME_SCREEN_WIDTH
#define GAME_PLAYFIELD_HEIGHT \
    (GAME_SCREEN_HEIGHT - GAME_HUD_HEIGHT)

#endif
